SELECT SUM(MMONEY) MMONEY 
	FROM MILEAGE
	WHERE ID = 'test01' AND MSTATE = 'P';
	
SELECT MSEQ ,ID ,MMONEY ,MDATE ,MSTATE 
	FROM MILEAGE m 
	WHERE ID = 'test01';
	
--반환
UPDATE MILEAGE 
	SET MMONEY = (SELECT PAYMENTAMT FROM PAYMENT WHERE PAYMENTNUM = 'P002'), MSTATE = 'P', MDATE = SYSDATE 
	WHERE MSEQ = '3';
	
--적립
INSERT INTO MILEAGE (MSEQ,ID,MMONEY,MDATE,MSTATE)
VALUES(MSEQ_SEQ.NEXTVAL,'test01',(SELECT FLOOR(PAYMENTAMT *0.01) FROM PAYMENT WHERE PAYMENTNUM = 'P002'),SYSDATE, 'P');

SELECT FLOOR(PAYMENTAMT *0.01) FROM PAYMENT WHERE PAYMENTNUM = 'P002';

SELECT c.COUPON, c.CNOTIFY, c2.CBDATE
	FROM COUPON c, COUPONBOX c2 
	WHERE  c2.ID = 'test01';
	
INSERT INTO MILEAGE (MSEQ,ID,MMONEY,MDATE,MSTATE)
VALUES(MSEQ_SEQ.NEXTVAL,'test01',(SELECT FLOOR(PAYMENTAMT *0.01) FROM PAYMENT WHERE PAYMENTNUM = 'P002'),SYSDATE, 'P');

SELECT SUM(MMONEY) 
	FROM MILEAGE
	WHERE ID = 'test01' AND MSTATE = 'P';
	
SELECT c2.CNOTIFY, c2.coupon, c2.cdate, c2.CIMG FROM COUPONBOX c, COUPON c2  WHERE c.CSEQ = c2.CSEQ AND ID = 'test01' AND c2.CENABLE = 'Y'


ALTER TABLE COUPON ADD CIMG VARCHAR2(200) NULL;
ALTER TABLE COUPON ADD CTHUMBIMG VARCHAR2(200) NULL;




