INSERT INTO PAYMENT
(PAYMENTNUM, ONUM, SALEAMT, DISCOUNTAMT, PAYMENTAMT, PAYMENTDATE)
VALUES(PAYMENTNUM_SEQ.NEXTVAL, (SELECT ONUM FROM "ORDER" o  WHERE ONUM ='63') ,(SELECT ODSTOCK*OPRICE FROM ORDERDETAIL o WHERE ICODE = '1002'), 
(SELECT SUM(MMONEY) MMONEY FROM MILEAGE m)+(SELECT c.COUPON FROM COUPON c WHERE CSEQ = '41'), 
(SELECT ODSTOCK*OPRICE FROM ORDERDETAIL o WHERE ICODE = '1002')-((SELECT SUM(MMONEY) MMONEY FROM MILEAGE m)+(SELECT c.COUPON FROM COUPON c WHERE CSEQ = '41')), SYSDATE);


SELECT ONUM FROM "ORDER" o  WHERE ONUM ='63';
SELECT ODSTOCK*OPRICE FROM ORDERDETAIL o WHERE ICODE = '1002';

SELECT SUM(MMONEY) - '90' 
	FROM MILEAGE m 
	WHERE MSTATE = 'P' ;

SELECT c.COUPON FROM COUPON c WHERE CSEQ = '41';
	
SELECT *
	FROM MILEAGE m ;
	


-- 결제 완료 시 결제내역 페이지 추가
INSERT INTO PAYMENT
(PAYMENTNUM, ONUM, SALEAMT, DISCOUNTAMT, PAYMENTAMT, PAYMENTDATE)
VALUES(PAYMENTNUM_SEQ.NEXTVAL, (SELECT ONUM FROM "ORDER" o  WHERE ONUM ='63') ,(SELECT ODSTOCK*OPRICE FROM ORDERDETAIL o WHERE ICODE = '1002'), 
(SELECT MMONEY FROM MILEAGE m WHERE MSTATE ='M' AND MSEQ ='63')+(SELECT c.COUPON FROM COUPON c WHERE CSEQ = '41'), 
(SELECT ODSTOCK*OPRICE FROM ORDERDETAIL o WHERE ICODE = '1002')-((SELECT MMONEY FROM MILEAGE m WHERE MSTATE ='M' AND MSEQ ='63')+(SELECT c.COUPON FROM COUPON c WHERE CSEQ = '41')), SYSDATE);


INSERT INTO MILEAGE ( MSEQ,ID,MMONEY,MDATE,MSTATE)
VALUES(MSEQ_SEQ.NEXTVAL,'test01','20',SYSDATE,'M');

UPDATE MILEAGE m SET  m.MMONEY = (SELECT SUM(MMONEY) - '20' FROM MILEAGE m2) , m.ID ='test01';

INSERT INTO MILEAGE 

SELECT MMONEY FROM MILEAGE m WHERE MSTATE ='M' AND MSEQ ='63';

DELETE FROM MILEAGE m WHERE MSEQ ='64';


SELECT TO_DATE(ODATE) ODATE , o.ONUM ,i.INAME ,
	   o2.ODSTOCK ,o2.OPRICE ,o.STORE ,
	   o.OSTATE ,m.NAME ,o.ADDR , 
	   m.PHONE , p.PAYMENTAMT , p.DISCOUNTAMT 
		FROM "ORDER" o 
		INNER JOIN ORDERDETAIL o2 ON o2.ONUM = o.ONUM 
		INNER JOIN INVENTORY i ON i.ICODE = o2.ICODE 
		INNER JOIN "MEMBER" m ON m.ID = o.ID 
		INNER JOIN PAYMENT p ON p.ONUM = o.ONUM 
		WHERE o.ONUM = '63';
		
SELECT * FROM "ORDER" o WHERE ONUM = '63';
		