SELECT * FROM coupon;

SELECT * FROM COUPONBOX;

CREATE SEQUENCE AUTOORDER_SEQ START WITH 1 INCREMENT BY 1;

SELECT TO_DATE(ODATE) ODATE , o.ONUM ,i.INAME ,
	   o2.ODSTOCK ,o2.OPRICE ,o.STORE ,
	   o.OSTATE ,m.NAME ,o.ADDR , 
	   m.PHONE , p.PAYMENTAMT , p.DISCOUNTAMT 
	FROM "ORDER" o 
	INNER JOIN ORDERDETAIL o2 ON o2.ONUM = o.ONUM 
	INNER JOIN INVENTORY i ON i.ICODE = o2.ICODE 
	INNER JOIN "MEMBER" m ON m.ID = o.ID 
	INNER JOIN PAYMENT p ON p.ONUM = o.ONUM 
	WHERE o.ONUM = '50';