INSERT INTO PAYMENT
(PAYMENTNUM, ONUM, SALEAMT, DISCOUNTAMT, PAYMENTAMT, PAYMENTDATE)
VALUES(PAYMENTNUM_SEQ.NEXTVAL, (SELECT ONUM FROM "ORDER" o  WHERE ONUM ='63') ,(SELECT ODSTOCK*OPRICE FROM ORDERDETAIL o WHERE ICODE = '1002'), 
(SELECT SUM(MMONEY) MMONEY FROM MILEAGE m)+(SELECT c.COUPON FROM COUPON c WHERE COUPON = '1000'), 
(SELECT ODSTOCK*OPRICE FROM ORDERDETAIL o WHERE ICODE = '1002')-((SELECT SUM(MMONEY) MMONEY FROM MILEAGE m)+(SELECT c.COUPON FROM COUPON c WHERE COUPON = '1000')), SYSDATE);

CREATE SEQUENCE PAYMENTNUM_SEQ START WITH 1 INCREMENT BY 1;
DROP SEQUENCE COUPON_SEQ;

SELECT SUM(MMONEY) MMONEY FROM MILEAGE m;


SELECT ODSTOCK*OPRICE FROM ORDERDETAIL o WHERE ICODE = '1002';


-- 배송 추가
UPDATE "ORDER" SET ODATE = SYSDATE , ROADADDR = '406',  ADDR = '서울특별시', DELIVERYSELECT = 'Y', OSTATE ='P' WHERE ONUM ='53';

-- 배송 추가X
UPDATE "ORDER" SET ODATE = SYSDATE , ROADADDR = '',  ADDR = '', DELIVERYSELECT = 'N', OSTATE ='P' WHERE ONUM ='53';


SELECT c2.CBSEQ, c.CNOTIFY, c.CSEQ, c.COUPON FROM COUPON c, CouponBox c2 WHERE c.CSEQ = c2.CSEQ;



